### ISSUE TITLE
Update for LLVM 3.4 & CUDA 8.0

### ISSUE THREAD

**Issue by beckdav** [DependableSystemsLab/LLFI-GPU#3]
Hi, 
I have your software correctly working on my machine using the provided precompiled library and CUDA 6.0 but I have been trying to update your LLFI-GPU software so that it will work with CUDA 8.0. 

I have firstly been trying to recompile the cicc library to utilise my versions of LLVM 3.4 & CUDA 8.0.
I now have the code in a state so that the library compiles with no errors or warnings with LLVM 3.4 and CUDA 8.0 but it does not appear to be functioning correctly. 

When running the profile.py with the provided example.cu file with CUDA 8.0 no bamboo.profile.txt file or opt.bamboo_before/after.ll files are generated. 

After the makeCommand1 is performed with CUDA 6.0 "Profiling pass installed" is printed to the terminal however when running using CUDA 8.0 this line is never printed ... 

This leads me to believe it is an issue with regard to the cicc library however I am not very experienced with cpp or libraries and would greatly appreciate any advise or idea you might have on the matter. 

Kind Regards, 
beckdav

**Comment by beckdav** [comment]
Hi, 
I have uploaded my modified version of LLFI-GPU to my GitHub here: https://github.com/beckdav/LLFI-GPU-LLVM3.4
This version in fact still uses cuda-6.0 but LLVM 3.4 with no success, 
I get a runtime error of this: 

***[GPGPU-BAMBOO]*** Generating Profiling Pass ... 
cicc: symbol lookup error: ./libcicc.so: undefined symbol: _ZN4llvm14raw_fd_ostreamC1EPKcRSsNS_3sys2fs9OpenFlagsE
ptxas fatal   : Input file '/tmp/tmpxft_00001e04_00000000-5_example.ptx' could not be opened
ptxas fatal   : Ptx assembly aborted due to errors
nvlink fatal   : Could not open input file 'example.o'
***[GPGPU-BAMBOO]*** Generating Profiling Traces ... 
rm: cannot remove ‘bamboo.profile.txt’: No such file or directory
/bin/sh: 1: ./example.out: not found
Traceback (most recent call last):
  File "profile.py", line 80, in <module>
    main()
  File "profile.py", line 76, in main
    runProfile();
  File "profile.py", line 50, in runProfile
    goldenOutput = subprocess.check_output("./" +outputExeFile+ " " + inputParameters, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command './example.out ' returned non-zero exit status 127

**Comment by cclinus** [comment]
My understanding is that CUDA6 is compatible with LLVM3.0, not sure if it is compatible with LLVM3.4 (Probably not). Neither are we sure which LLVM version CUDA8 is compatible with. If you can find it out and get it tested, you are welcome to submit it to us.

Just curious, why you are looking for particular LLVM and CUDA version for fault injection study ? Is there anything that you consider to do in these version but can not do it with CUDA6 and LLVM3.0 ?

Thanks
