### ISSUE TITLE
FI config parameters

### ISSUE THREAD

**Issue by bbabatunde** [DependableSystemsLab/LLFI-GPU#5]
I am confused about what this actually does during the fault injection process, I cannot find any hints in the paper

staticInstIndex = "" # fiInstIndex=20 or ""
staticKernelIndex = "" # 5 or ""
dynamicKernelIndex = "" # 3 or ""
bitIndex = "" # 63 or "

**Comment by cclinus** [comment]
Thanks for asking.

LLFI-GPU is able to configure in the way to inject fault at specific kernel, instruction, and bit. So these variables can be set to do so. The example of config. is shown in each comment line. If these config is specified, LLFI-GPU will no longer randomly choose place to inject faults, instead, it will inject faults to the place you specified.

**Comment by bbabatunde** [comment]
Thanks.
Do you have any idea about how to go about printing out instruction that the fault injection is been perform on?

**Comment by cclinus** [comment]
What is the goal ? Can you elaborate it ?

If you are wondering where the faults were injected exactly at every FI run, they are logged in the stat file already.

**Comment by bbabatunde** [comment]
So in the inject.py , a random instruction is been selected and used for the injection right? 

here

fiInstCount = random.randint(1, totalInstCount)

I want to be able to identify what instruction that is and print it out

**Comment by cclinus** [comment]
You can obviously add a print after this line of code. But, these info are already logged at the log file generated after fault injection. Usually a static instruction index is logged, and you can find it in the IR file generated, this index is mapped at bamboo_index meta data after each static instruction.

**Comment by cclinus** [comment]
The FI log file is in bamboo_fi/bamboo.fi.log.txt

**Comment by bbabatunde** [comment]
My aim is not to print the fiInstCount integer/Number but the Cuda instruction or anything that will give me an idea what operation is been manipulated.

**Comment by cclinus** [comment]
Right, so you should look at which index it is and find it in the IR code.

For example, if the staticInstIndex is 30, it means LLFI-GPU injects fault to LLVM IR instruction that has index 30 on it. So you need to see the IR file (i.e, bamboo_fi/example_kernel.ll) and find the instrcution ending with things like "!bamboo_fi index = 30", and that is the instruction you just injected, say it is a "add" LLVM instruction.

**Comment by bbabatunde** [comment]
oh thanks
